export const REQUEST_MOVIES_BY_KEYWORD = "REQUEST_MOVIES_BY_KEYWORD";
export const SUCCESS_GET_MOVIES_BY_KEYWORD = "SUCCESS_GET_MOVIES_BY_KEYWORD";
export const FAILED_GET_MOVIES_BY_KEYWORD = "FAILED_GET_MOVIES_BY_KEYWORD";

export const REQUEST_MOVIES_BY_TITLE = "REQUEST_MOVIES_BY_TITLE";
export const SUCCESS_GET_MOVIES_BY_TITLE = "SUCCESS_GET_MOVIES_BY_TITLE";
